export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

//Promise have 3 states
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';

export const REQUEST_JOKE_PENDING = 'REQUEST_JOKE_PENDING';
export const REQUEST_JOKE_SUCCESS = 'REQUEST_JOKE_SUCCESS';
export const REQUEST_JOKE_FAILED = 'REQUEST_JOKE_FAILED';

export const PLAYER_DONE_LOADING = 'PLAYER_DONE_LOADING';